title: Hannah's
tagline: ""
description: "New Ideas Meet Talents."
url: https://hannah803.github.io
paginate: 5
permalink: pretty

# About/contact
author:
  name: Hannah
  url: https://hannah803.github.io
  email: hui.liu803@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version: 1.1.0

